VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes # reduce firmware size

CONSOLE_ENABLE = no
COMMAND_ENABLE = no

#SPACE_CADET_ENABLE = no
#GRAVE_ESC_ENABLE = no
#MAGIC_ENABLE = no
#QMK_SETTINGS = no

#MOUSEKEY_ENABLE = no
#MUSIC_ENABLE = no

#KEY_OVERRIDE_ENABLE = no
#COMBO_ENABLE = no
#TAP_DANCE_ENABLE = no
